module.exports = {
    AUTH_SERVICE: 'authService',
    USER_SERVICE: 'userService',
    TOKEN_SERVICE: 'tokenService',
    PASSWORD_HASHING_SERVICE: 'passwordHashingService',
    PLAN_SERVICE: 'planService',
    KIND_SERVICE: 'kindService',
    DATE_PLAN_SERVICE: 'datePlanService',
    IMAGE_SERVICE: 'imageService',
    PROVINCE_SERVICE: 'provinceService',
    ACTIVITY_LOCATION_SERVICE: 'activityLocationService',
    SLACK_SERVICE: 'slackService',
    GEMINI_SERVICE: 'geminiService',
    WEATHER_SERVICE: 'weatherService',
}